In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
df = pd.read_excel("/content/DatasetforDataAnalytics.xlsx")
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [17]:
# Format 'Date' column as a string
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')

# Split 'ShippingAddress' into house number and street name
# Assuming address format is 'NUMBER StreetName'
df['ShippingAddressNumber'] = df['ShippingAddress'].apply(lambda x: int(x.split(' ')[0]))
df['ShippingStreetName'] = df['ShippingAddress'].apply(lambda x: ' '.join(x.split(' ')[1:]))


# Drop original 'ShippingAddress' column as requested
df = df.drop(columns=['ShippingAddress'])

# Reorder columns for better readability
desired_order = [
    'OrderID', 'Date', 'CustomerID', 'Product',
    'Quantity', 'UnitPrice', 'ShippingAddressNumber', 'ShippingStreetName',
    'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart',
    'CouponCode', 'ReferralSource', 'TotalPrice'
]

# Add any other existing columns not explicitly mentioned in desired_order to the end
existing_cols = df.columns.tolist()
final_order = [col for col in desired_order if col in existing_cols] + \
              [col for col in existing_cols if col not in desired_order]
df = df[final_order]

print("DataFrame after transformations and reordering:")
display(df.head())
display(df.info())

DataFrame after transformations and reordering:

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddressNumber,ShippingStreetName,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928,Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823,Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512,Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275,Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668,Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   OrderID                1200 non-null   object
 1   Date                   1200 non-null   object
 2   CustomerID             1200 non-null   object
 3   Product                1200 non-null   object
 4   Quantity               1200 non-null   int64
 5   UnitPrice              1200 non-null   float64
 6   ShippingAddressNumber  1200 non-null   int64
 7   ShippingStreetName     1200 non-null   object
 8   PaymentMethod          1200 non-null   object
 9   OrderStatus            1200 non-null   object
 10  TrackingNumber         1200 non-null   object
 11  ItemsInCart            1200 non-null   int64
 12  CouponCode             891 non-null    object
 13  ReferralSource         1200 non-null   object
 14  TotalPrice             1200 non-null   float64
dtypes: float64(2), int64(3), object(10)
memory usage: 140.8+ KB

None

In [18]:
# List the columns that should be categories
category_cols = ['PaymentMethod', 'OrderStatus', 'ReferralSource']

# Convert them to the category data type
df[category_cols] = df[category_cols].astype('category')

# Optional: Run a quick check to confirm the types have updated
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   OrderID                1200 non-null   object
 1   Date                   1200 non-null   object
 2   CustomerID             1200 non-null   object
 3   Product                1200 non-null   object
 4   Quantity               1200 non-null   int64
 5   UnitPrice              1200 non-null   float64
 6   ShippingAddressNumber  1200 non-null   int64
 7   ShippingStreetName     1200 non-null   object
 8   PaymentMethod          1200 non-null   category
 9   OrderStatus            1200 non-null   category
 10  TrackingNumber         1200 non-null   object
 11  ItemsInCart            1200 non-null   int64
 12  CouponCode             891 non-null    object
 13  ReferralSource         1200 non-null   category
 14  TotalPrice             1200 non-null   float64
dtypes: category(3), float64(2), int64(3), object(7)
memory usage: 116.8+ KB

In [19]:
df.describe()

,Quantity,UnitPrice,ShippingAddressNumber,ItemsInCart,TotalPrice
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,2.945833,356.412750,561.195833,5.485000,1053.968300
std,1.407557,197.177146,267.464995,2.281983,819.856558
min,1.000000,11.390000,100.000000,1.000000,11.390000
25%,2.000000,186.062500,326.750000,4.000000,410.520000
50%,3.000000,364.210000,562.500000,5.000000,823.615000
75%,4.000000,521.570000,803.250000,7.000000,1578.475000
max,5.000000,699.930000,999.000000,10.000000,3456.400000

In [20]:
df.skew(numeric_only=True)

Quantity                 0.027922
UnitPrice               -0.026512
ShippingAddressNumber   -0.039950
ItemsInCart              0.000877
TotalPrice               0.891359
dtype: float64

In [21]:
df.isnull().sum()

OrderID                    0
Date                       0
CustomerID                 0
Product                    0
Quantity                   0
UnitPrice                  0
ShippingAddressNumber      0
ShippingStreetName         0
PaymentMethod              0
OrderStatus                0
TrackingNumber             0
ItemsInCart                0
CouponCode               309
ReferralSource             0
TotalPrice                 0
dtype: int64

In [22]:
df['CouponCode'] = df['CouponCode'].fillna('No Coupon')

In [23]:
df.duplicated().sum()

np.int64(0)

In [26]:
# 1. Check how many duplicate Order IDs exist
duplicate_orders = df['OrderID'].duplicated().sum()
print(f"Duplicate Order IDs found: {duplicate_orders}")

Duplicate Order IDs found: 0

In [24]:
from IPython.display import display, HTML

results = []
for col in df.columns:
        unique_vals = df[col].unique()
        num_unique = len(unique_vals)
        # Limit the display of unique values to avoid excessively long outputs
        if num_unique > 10:
            display_vals = ', '.join(map(str, unique_vals[:5])) + ', ...'
        else:
            display_vals = ', '.join(map(str, unique_vals))
        results.append({'Column': col, 'Number of Unique Values': num_unique, 'Unique Values (Sample/All)': display_vals})

unique_df = pd.DataFrame(results)
display(HTML(unique_df.to_html(index=False)))

In [27]:
# 1. Dates: Lock into ISO 8601 Format (YYYY-MM-DD)
# This forces the datetime object into a strict text format
df['Date'] = pd.to_datetime(df['Date']).dt.strftime('%Y-%m-%d')

# 2. Text: Trim whitespace and apply Proper Case (Title Case)
# We will loop through your main text categories
text_cols = ['Product', 'PaymentMethod', 'OrderStatus', 'ReferralSource', 'ShippingStreetName']

for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

# If you converted these to categories earlier, you can lock them back into categories:
category_cols = ['PaymentMethod', 'OrderStatus', 'ReferralSource']
df[category_cols] = df[category_cols].astype('category')

# 3. Numbers: Numeric Precision to exactly 2 decimal places
df['UnitPrice'] = df['UnitPrice'].round(2)
df['TotalPrice'] = df['TotalPrice'].round(2)

In [28]:
from IPython.display import display, HTML

results = []
for col in df.columns:
        unique_vals = df[col].unique()
        num_unique = len(unique_vals)
        # Limit the display of unique values to avoid excessively long outputs
        if num_unique > 10:
            display_vals = ', '.join(map(str, unique_vals[:5])) + ', ...'
        else:
            display_vals = ', '.join(map(str, unique_vals))
        results.append({'Column': col, 'Number of Unique Values': num_unique, 'Unique Values (Sample/All)': display_vals})

unique_df = pd.DataFrame(results)
display(HTML(unique_df.to_html(index=False)))